export type LatLng = [number, number];
export interface Checkpoint { id: string; order: number; name: string; kind: string; distM: number; lat: number; lng: number; radiusM: number; reward: boolean; dataSource?: string | null }
export interface Poi { id?: string; contentId: string | null; contentTypeId: number; type?: string; title: string; addr1: string | null; lat: number; lng: number; dist?: number; firstImage: string | null; overview?: string | null; source?: string }
export interface CoursePoi { courseId: string; poiId: string; distFromStartM: number; triggerRadiusM: number; voice: string | null; poi: Poi }
export interface Course { id: string; slug: string; name: string; description: string; distanceM: number; difficulty: string; themes: string[]; areaName: string; startLat: number; startLng: number; polyline: LatLng[]; elevationGainM: number; estMinutes: number; source: 'OFFICIAL' | 'USER'; isPublic: boolean; checkpoints?: Checkpoint[]; pois?: CoursePoi[]; _count?: { checkpoints: number; runs: number } }
export interface Weather { source: string; airSource: string; temp: number; humidity: number; windMs: number; rainType: string; sky: string; pm10: number | null; pm10Grade: string; sunset: string; error?: string }
export interface Recommendation { weather: Weather; input: { km: number; themes: string[]; hourKst: number }; best: { course: Pick<Course, 'id' | 'slug' | 'name' | 'distanceM' | 'difficulty' | 'themes' | 'estMinutes' | 'source'>; score: number; reasons: string[] } | null; candidates: { course: any; score: number; reasons: string[] }[] }
export interface NearbyResult { source: 'TOURAPI' | 'SEED'; fetchedMs: number; endpoint: string; items: Poi[]; raw?: unknown; error?: string }
export interface RunTrackPoint { lat: number; lng: number; t: number; accuracy?: number }
export interface Run { id: string; courseId: string; mode: 'DEMO' | 'LIVE'; status: string; startedAt: string; distanceM: number; durationSec: number }
export interface ActiveRun extends Run { track: RunTrackPoint[] | null; course: Course; checkins: { checkpointId: string }[] }
export interface FinishSummary { valid: boolean; invalidReason: string | null; distanceM: number; durationSec: number; avgPaceSec: number; pace: string; checkins: number; checkpoints: number; medal: { code: string; name: string; description: string; isNew: boolean } | null; coupon: { code: string; title: string; discountKrw: number; merchant: string; validUntil: string } | null; challenge: { code: string; name: string; before: number; after: number; target: number } | null; missions: { code: string; title: string; type: string; value: number; done: boolean }[]; medalCollection: { code: string; name: string; earned: boolean; isNew: boolean }[]; profile: { totalKm: number; courses: number; medals: number } }
export const fmtTime = (sec: number) => { sec = Math.max(0, Math.round(sec)); const m = Math.floor(sec / 60), s = sec % 60; return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`; };
export const fmtPace = (secPerKm: number) => `${Math.floor(secPerKm / 60)}'${String(Math.round(secPerKm % 60)).padStart(2, '0')}"`;
export const fmtKm = (m: number) => (m / 1000).toFixed(m >= 10000 ? 1 : 2);
