ALTER TABLE "User"
ADD COLUMN "avatarUrl" TEXT,
ADD COLUMN "bio" TEXT,
ADD COLUMN "homeArea" TEXT NOT NULL DEFAULT '대구 수성구',
ADD COLUMN "weeklyGoalKm" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "preferredPaceSec" INTEGER,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
